#!/bin/bash
# Quick Commands Reference for Monorepo Migration

echo "==================================="
echo "Monorepo Migration - Quick Commands"
echo "==================================="
echo ""

echo "📋 STEP-BY-STEP MIGRATION COMMANDS"
echo "-----------------------------------"
echo ""

echo "1️⃣  Run the migration script:"
echo "   ./scripts/migrate-to-shared.sh"
echo ""

echo "2️⃣  Install dependencies:"
echo "   pnpm install"
echo ""

echo "3️⃣  Build shared packages:"
echo "   pnpm --filter \"@repo/*\" build"
echo ""

echo "4️⃣  Test each app:"
echo "   pnpm --filter mishrashardendu22 dev                # PersonalWebsite"
echo "   pnpm --filter mishrashardendu22-admin dev          # AdminWebsite"
echo "   pnpm --filter mishrashardendu22-blog dev           # BlogWebsite"
echo ""

echo "5️⃣  Build all apps:"
echo "   pnpm build"
echo ""

echo "-----------------------------------"
echo "📚 DOCUMENTATION"
echo "-----------------------------------"
echo ""
echo "Start here:      MIGRATION_GUIDE.md"
echo "Deep dive:       MONOREPO_OPTIMIZATION.md"
echo "Status:          IMPLEMENTATION_SUMMARY.md"
echo "This summary:    README_MONOREPO.md"
echo ""

echo "-----------------------------------"
echo "🔄 IMPORT UPDATE EXAMPLES"
echo "-----------------------------------"
echo ""
echo "UI Components:"
echo "  OLD: import { Button } from '@/components/ui/button'"
echo "  NEW: import { Button } from '@repo/shared-ui/components/button'"
echo ""
echo "Utilities:"
echo "  OLD: import { cn } from '@/lib/utils'"
echo "  NEW: import { cn } from '@repo/shared-utils/utils'"
echo ""
echo "Types:"
echo "  OLD: import type { Project } from '@/data/types.data'"
echo "  NEW: import type { Project } from '@repo/shared-types/data'"
echo ""
echo "Auth:"
echo "  OLD: import { authClient } from '@/lib/authClient'"
echo "  NEW: import { authClient } from '@repo/auth-shared/client'"
echo ""

echo "-----------------------------------"
echo "🗑️  FILES TO DELETE (After Migration)"
echo "-----------------------------------"
echo ""
echo "From PersonalWebsite:"
echo "  - src/app/blog/ (entire folder)"
echo "  - src/app/admin/* (admin pages)"
echo "  - src/components/blog/"
echo "  - src/components/ui/ (after migration)"
echo "  - src/util/api.ts"
echo "  - src/util/apiResponse.util.ts"
echo "  - src/data/types.data.ts"
echo ""
echo "From AdminWebsite:"
echo "  - src/components/ui/"
echo "  - src/utils/api.ts"
echo "  - src/utils/apiResponse.util.ts"
echo "  - src/types/types.data.ts"
echo "  - src/lib/utils.ts"
echo ""
echo "From BlogWebsite:"
echo "  - src/components/ui/"
echo "  - src/lib/utils.ts"
echo "  - src/lib/auth.ts"
echo "  - src/lib/authClient.ts"
echo "  - src/lib/authHelper.ts"
echo ""

echo "-----------------------------------"
echo "🐛 TROUBLESHOOTING"
echo "-----------------------------------"
echo ""
echo "Cannot find module '@repo/shared-*':"
echo "  pnpm install && pnpm build"
echo ""
echo "Type errors:"
echo "  pnpm --filter \"@repo/*\" build"
echo "  # Then restart TypeScript server in VS Code"
echo ""
echo "Import errors:"
echo "  # Check package.json has workspace dependencies"
echo "  # Verify imports use correct package names"
echo ""

echo "-----------------------------------"
echo "📊 EXPECTED RESULTS"
echo "-----------------------------------"
echo ""
echo "Code reduction:       ~10,000 lines removed"
echo "Build time:           15-20min → 10-12min (30-40% faster)"
echo "Bundle size:          20-30% smaller"
echo "Development speed:    2-3x faster iterations"
echo ""

echo "==================================="
echo "Ready to start? Run: ./scripts/migrate-to-shared.sh"
echo "==================================="
